clang-tidy: delete default constructor
Default constructor was invalid for class semantics and caused
clang-tidy/Clang diagnostics. Mark the default constructor as
`=delete` to prevent accidental default construction and keep
-Werror builds green. No functional changes.

Fixed below errors (example)
'''
../ikvm_input.hpp:32:12: error: explicitly defaulted copy assignment operator is implicitly deleted [-Werror,-Wdefaulted-function-deleted]
   32 |     Input& operator=(const Input&) = default;
      |            ^
'''

Change-Id: Ic6777c6b3f1820457151a33b176668d7da20ae63
Signed-off-by: Jayanth Othayoth <ojayanth@gmail.com>